openapi: 3.0.1
info:
  title: Zilch Card API
  version: '1.0'
paths:
  /zilch/cards:
    summary: Banking Api
    description: validate and add new card details in DB
    post:
      summary: validate and add new card details in DB
      description: This API validate and add new card details in DB
      operationId: 'addCardDetails'
      tags:
        - card
      requestBody:
        content:
          application/json:
            schema:
              type: object
              title: ZilchCardDetails
              properties:
                userId:
                  example: user123
                  description: unique user Id
                  type: string
                  minLength: 3
                  maxLength: 10
                userFirstName:
                  example: Dinesh
                  description: User First Name
                  type: string
                  minLength: 3
                  maxLength: 10
                userLastName:
                  example: Malik
                  description: User Last Name
                  type: string
                  minLength: 10
                  maxLength: 10
                cardNo:
                  type: string
                  example: 4417123456789113
                  description: user card no
                  minLength: 16
                  maxLength: 16
                expiryDate:
                  title: Date in ISO8201 format
                  type: string
                  example: '2024-02-02'
                  format: date
                  description: expiry date of issued card in pattern DD-MM-YYYY
                cvv:
                  type: integer
                  example: 123
                  description: cvv of the issued card
                  minLength: 3
                  maxLength: 3
      responses:
        '200':
          description: Response on creating the account
          $ref: '#/components/responses/zilchCardResponse'
        default:
          $ref: '#/components/schemas/ApiError'
  /zilch/cards/card:
    summary: Banking Api
    description: get details of the card using userId and ending 4 digits
    get:
      summary: get details of the card using userId and ending 4 digits
      description: This API get details of the card using userId and ending 4 digits
      operationId: 'getCardDetails'
      parameters:
        - name: userId
          in: header
          required: true
          schema:
            type: string
        - name: last4Digit
          in: header
          required: true
          schema:
            type: string
      tags:
        - card
      responses:
        '200':
          description: response of Card Api
          $ref: '#/components/responses/zilchCardDetailsResponse'
components:
  responses:
    zilchCardResponse:
      description: Response on adding the card details
      content:
        application/json:
          schema:
            type: object
            title: zilchCardResponse
            properties:
              last4Digit:
                type: string
                example: 7457
                description: last 4 digits of created record
    zilchCardDetailsResponse:
      description: Response of the card details get endpoint
      content:
        application/json:
          schema:
            type: object
            title: zilchCardDetailsResponse
            properties:
              last4Digit:
                type: string
                example: 7457
                description: last 4 digits of created record
              userFirstName:
                type: string
                example: Dinesh
                description: first Name of user
              userLastName:
                type: string
                example: Malik
                description: user last Name
  requestBodies:
    accountCreation:
      content:
        application/json:
          schema:
            type: object
            properties:
              userId:
                example: user123
                description: unique user Id
                type: string
                minLength: 3
                maxLength: 10
              userFirstName:
                example: Dinesh
                description: User First Name
                type: string
                minLength: 3
                maxLength: 10
              userLastName:
                example: Malik
                description: User Last Name
                type: string
                minLength: 10
                maxLength: 10
              cardNo:
                type: string
                example: 4417123456789113
                description: user card no
                minLength: 16
                maxLength: 16
              expiryDate:
                title: Date in ISO8201 format
                type: string
                example: '2024-02-02'
                format: date
                description: expiry date of issued card
              cvv:
                type: integer
                example: 123
                description: cvv of the issued card
                minLength: 3
                maxLength: 3
  schemas:
    ApiError:
      type: object
      properties:
        status:
          type: integer
          description: The HTTP response code
          example: 400
        detail:
          type: string
          description: A human-readable description of the error
          example: Validation errors found in request body
        code:
          type: string
          description: an error code which will uniquely identify the error
          example: CARD_API_ERR_400_1